name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: npm i
  
      - name: Ejecutar pruebas
        run: npm test

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Azure login
        if: ${{ job.status == 'success' }}
        uses: Azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS}}
          
      - name: Configurar CLI de Azure
        run: az configure --defaults acr=acrAndresMayor
        
      - name: Configurar entorno de Docker
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.LOGIN_SERVER}}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
  
      - name: Construir y etiquetar la imagen de Docker
        run: |
          docker build -t twitter-front .
          docker tag twitter ${{ secrets.LOGIN_SERVER}}/twitter:${{ github.sha }}
          
      - name: Subir imagen al ACR
        run: docker push ${{ secrets.LOGIN_SERVER}}/twitter:${{ github.sha }}
      
      - name: kubectl-simple
        uses: steebchen/kubectl@v2.1.1
        with:
          config: ${{ secrets.KUBECONFIG }} 
          command: set image -n proyecto deployment/front front=acrandresmayor.azurecr.io/frontend:${{ github.sha }}

