name: Docker Image CI

on:
  push:
    branches:
      - feature/*
      - develop
      - main
    
  pull_request:
    branches:
      - feature/*
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: npm i

      - name: Run Tests      
        run: npm test               

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3.0.0

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: |      
      github.ref == 'refs/heads/feature/*' && github.event_name == 'pull_request' && github.base_ref == 'refs/heads/develop' ||
      github.ref == 'refs/heads/develop' && github.event_name == 'push' ||
      github.ref == 'refs/heads/develop' && github.event_name == 'pull_request' && github.base_ref == 'refs/heads/main' ||
      github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'pull_request') ||
      github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Tag Docker Image
        run: |
          docker build -t twitter .
          docker tag twitter ${{ secrets.LOGIN_SERVER }}/twitter:latest
          docker tag twitter ${{ secrets.LOGIN_SERVER }}/twitter:${{ github.sha }}
                  
      - name: Push Image to ACR
        run: |
          docker push ${{ secrets.LOGIN_SERVER }}/twitter:latest
          docker push ${{ secrets.LOGIN_SERVER }}/twitter:${{ github.sha }}
