name: Docker Image CI

on:
  push:
    branches:
      - feature/*
      - develop
      - main
      - master
  pull_request:
    branches:
      - feature/*
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: npm i
  
      - name: Run Tests      
        run: npm test     
        if: github.ref == 'refs/heads/develop' || (github.event_name == 'pull_request' && github.base_ref == 'refs/heads/develop')    

      - name: SonarScanner
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3.0.0

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:

      #- name: Install Azure CLI
       # run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  
      #- name: Azure login
       # if: ${{ job.status == 'success' }}
        #uses: Azure/login@v1.4.6
        #with:
         # creds: ${{ secrets.AZURE_CREDENTIALS }}
          #enable-AzPSSession: true
      
      #- name: Configure Azure CLI
       # run: az configure --defaults acr=${{ secrets.ACR_NAME }}
      
      - name: Configure Docker Environment
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      - name: Build and Tag Docker Image
        run: |
          docker build -t twitter-front .
          docker tag twitter ${{ secrets.LOGIN_SERVER }}/twitter:${{ github.sha }}
                  
      - name: Push Image to ACR
        run: docker push ${{ secrets.LOGIN_SERVER }}/twitter:${{ github.sha }}
